---
services:
  documentdb-mcp:
    image: docker.io/knucklessg1/documentdb-mcp:latest
    # build: . # Debug
    container_name: documentdb-mcp
    hostname: documentdb-mcp
    command: ["documentdb-mcp"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - documentdb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8015"
      - "TRANSPORT=streamable-http"
      - "MONGODB_URI=${MONGODB_URI}" # Required
    ports:
      - "8015:8015"

  documentdb-agent:
    image: docker.io/knucklessg1/documentdb-mcp:latest
    # build: . # Debug
    container_name: documentdb-agent
    hostname: documentdb-agent
    command: ["documentdb-agent"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - documentdb-mcp
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
      - "HOST=0.0.0.0"
      - "PORT=9015"
      - "MCP_URL=http://documentdb-mcp:8015/mcp"
      - "PROVIDER=openai"
      - "OPENAI_BASE_URL=http://host.docker.internal:1234/v1"
      - "OPENAI_API_KEY=llama"
      - "MODEL_ID=qwen/qwen3-4b-2507"
      - "DEBUG=False"
      - "ENABLE_WEB_UI=True"
    ports:
      - "9015:9015"

  documentdb:
    image: ghcr.io/microsoft/documentdb/documentdb-local:latest
    container_name: documentdb
    hostname: documentdb
    environment:
      - USERNAME=${DOCUMENTDB_USERNAME:-administrator}
      - PASSWORD=${DOCUMENTDB_PASSWORD:-documentdbadmin}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mcp/documentdb-data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "10260:10260"
